docs: clarify error messages and job names

diff --git a/src/commands/login.yml b/src/commands/login.yml
--- a/src/commands/login.yml
+++ b/src/commands/login.yml
@@ -16,7 +16,7 @@ parameters:
 
 steps:
   - run:
-      name: Check environment variables
+      name: Checking for Vault environment variables
       command: |
         echo "Checking for the existence of Vault Environment Variables"
         [ -z "$<<parameters.vault-addr>>" ] && ERROR=true && \
@@ -30,14 +30,16 @@ steps:
           echo "Found <<parameters.vault-secret-id>>: **HIDDEN**"
 
         echo
-        [ -n "$ERROR" ] && \
-          echo "ERROR:" && \
-          echo && \
-          echo "You should check your projects Environment Variables page to see if you set <<parameters.vault-addr>>, <<parameters.vault-role-id>> and  <<parameters.vault-secret-id>>." && \
-          echo && \
-          exit 1 || \
+        if [[ -n "$ERROR" ]]; then
+          echo "ERROR:"
+          echo
+          echo "You should check your projects Environment Variables page to see if you set <<parameters.vault-addr>>, <<parameters.vault-role-id>> and  <<parameters.vault-secret-id>>."
+          echo
+          exit 1
+        else
           echo "Environment variables look all good."
-        echo
+          echo
+        fi
   - run:
       name: Login to Vault
       command: |
